# Generated by Django 3.2.4 on 2021-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Genel', max_length=30, verbose_name='konu'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
